import { useState } from 'react'
import { CalendarDays, Users, LayoutDashboard, ClipboardList, Repeat2, LogOut, Bell, Plus, ChevronLeft, ChevronRight, Clock3, AlertTriangle, CheckCircle2, Umbrella, Menu, X, UserRound, ArrowRight } from 'lucide-react'
import { days, employees, schedule, type Employee } from './data'

type Page='Dashboard'|'Employees'|'Base Schedule'|'Weekly Schedule'|'Time-Off Requests'|'Open Shifts'
const nav: {name:Page; icon:typeof CalendarDays}[]=[{name:'Dashboard',icon:LayoutDashboard},{name:'Employees',icon:Users},{name:'Base Schedule',icon:Repeat2},{name:'Weekly Schedule',icon:CalendarDays},{name:'Time-Off Requests',icon:ClipboardList},{name:'Open Shifts',icon:Clock3}]
const person=(id:number|null)=>employees.find(e=>e.id===id)

function App(){
 const [role,setRole]=useState<'login'|'manager'|'employee'>('login')
 const [page,setPage]=useState<Page>('Dashboard'); const [mobile,setMobile]=useState(false)
 if(role==='login') return <Login onLogin={setRole}/>
 if(role==='employee') return <EmployeeView onLogout={()=>setRole('login')}/>
 return <div className="shell"><aside className={mobile?'open':''}><div className="brand"><span className="brandmark">M</span><div>Motel Schedule<small>Maker</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(({name,icon:Icon})=><button className={page===name?'active':''} onClick={()=>{setPage(name);setMobile(false)}} key={name}><Icon/> {name}{name==='Time-Off Requests'&&<b>3</b>}{name==='Open Shifts'&&<b>1</b>}</button>)}</nav><div className="profile"><div className="avatar">AD</div><div><strong>Alex Dawson</strong><small>Manager</small></div><button onClick={()=>setRole('login')} title="Log out"><LogOut/></button></div></aside><main><header><button className="menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{page}</h1><p>{page==='Dashboard'?'Here’s what’s happening at your motel today.':page==='Weekly Schedule'?'Review coverage and hours for this week.':`Manage ${page.toLowerCase()} in one place.`}</p></div><div className="header-actions"><button className="iconbtn"><Bell/><i/></button><button className="primary" onClick={()=>setPage(page==='Employees'?'Employees':'Weekly Schedule')}><Plus/> {page==='Employees'?'Add employee':'Adjust schedule'}</button></div></header><section className="content">{page==='Dashboard'?<Dashboard go={setPage}/>:page==='Weekly Schedule'||page==='Base Schedule'?<Schedule base={page==='Base Schedule'}/>:page==='Employees'?<Employees/>:page==='Time-Off Requests'?<Requests/>:<OpenShifts/>}</section></main></div>
}

function Login({onLogin}:{onLogin:(r:'manager'|'employee')=>void}){return <div className="login"><section className="login-art"><div className="login-brand"><span className="brandmark">M</span>Motel Schedule <b>Maker</b></div><div className="art-copy"><span>Simple scheduling. Happier teams.</span><h1>Your motel,<br/>perfectly staffed.</h1><p>Keep your team in sync without the spreadsheets, group texts, or guesswork.</p></div><div className="mini-schedule"><div><b>This week</b><span>October 5 – 11</span></div><div className="mini-days">{['MON','TUE','WED','THU','FRI'].map((d,i)=><span key={d}><small>{d}</small><b>{5+i}</b><i className={i===2?'today':''}/></span>)}</div></div></section><section className="login-form"><div><span className="eyebrow">WELCOME BACK</span><h2>Sign in to your account</h2><p>Choose a demo view to explore the application.</p><label>Email address<input defaultValue="manager@seabreezemotel.com" /></label><label>Password<input type="password" defaultValue="password" /></label><button className="signin" onClick={()=>onLogin('manager')}>Sign in as manager <ArrowRight/></button><div className="or"><span/>or explore as<span/></div><button className="employee-demo" onClick={()=>onLogin('employee')}><UserRound/> Employee demo</button><small className="demo-note">This is a local demo. No account or data is sent anywhere.</small></div></section></div>}

function Dashboard({go}:{go:(p:Page)=>void}){return <><div className="datebar"><CalendarDays/><div><strong>Monday, October 5</strong><span>Week 41 · Oct 5 – Oct 11</span></div><button onClick={()=>go('Weekly Schedule')}>View full schedule <ArrowRight/></button></div><div className="stats"><Stat icon={Users} n="6" label="Working today" sub="3 shifts fully covered" color="green"/><Stat icon={Umbrella} n="3" label="Time-off requests" sub="Waiting for your review" color="gold"/><Stat icon={AlertTriangle} n="1" label="Open shift" sub="Friday · Day shift" color="red"/><Stat icon={Clock3} n="2" label="Below target" sub="Need more scheduled hours" color="blue"/></div><div className="dashboard-grid"><div className="panel today"><PanelHead title="Today’s schedule" action="View week" onClick={()=>go('Weekly Schedule')}/>{schedule.Monday.map(s=><div className="today-row" key={s.type}><span className={`shift-dot ${s.type.split(' ')[0].toLowerCase()}`}/><div><strong>{s.type} Shift</strong><small>{s.time}</small></div>{person(s.employee)&&<Person employee={person(s.employee)!}/>}<CheckCircle2 className="check"/></div>)}</div><div className="panel attention"><PanelHead title="Needs your attention"/><button onClick={()=>go('Time-Off Requests')}><span className="attention-icon gold"><Umbrella/></span><div><strong>3 time-off requests</strong><small>Oldest request is 2 days old</small></div><ArrowRight/></button><button onClick={()=>go('Open Shifts')}><span className="attention-icon red"><AlertTriangle/></span><div><strong>Friday day shift is open</strong><small>2 employees are eligible</small></div><ArrowRight/></button><button onClick={()=>go('Employees')}><span className="attention-icon blue"><Clock3/></span><div><strong>2 employees below target</strong><small>Marcus and Nina need hours</small></div><ArrowRight/></button></div></div><div className="panel hours"><PanelHead title="Team hours this week" action="View employees" onClick={()=>go('Employees')}/><div className="hour-grid">{employees.slice(0,4).map(e=><div className="hour" key={e.id}><Person employee={e}/><div className="progress"><span style={{width:`${Math.min(e.hours/e.target*100,100)}%`}} className={e.hours>e.target?'over':''}/></div><b>{e.hours}<small> / {e.target} hrs</small></b>{e.hours>e.target?<em className="bad">+{e.hours-e.target} overtime</em>:e.hours<e.target?<em>{e.target-e.hours} remaining</em>:<em className="good">On target</em>}</div>)}</div></div></>}
function Stat({icon:Icon,n,label,sub,color}:{icon:typeof Users;n:string;label:string;sub:string;color:string}){return <div className="stat"><span className={color}><Icon/></span><div><b>{n}</b><strong>{label}</strong><small>{sub}</small></div></div>}
function PanelHead({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panel-head"><h3>{title}</h3>{action&&<button onClick={onClick}>{action} <ArrowRight/></button>}</div>}
function Person({employee:e}:{employee:Employee}){return <div className="person"><span style={{background:e.color}}>{e.initials}</span><div><strong>{e.name}</strong><small>{e.role}</small></div></div>}

function Schedule({base}:{base:boolean}){return <><div className="schedule-toolbar"><div><button><ChevronLeft/></button><button className="today-button">Today</button><button><ChevronRight/></button></div><h2>October 5 – 11, 2026 <span>{base?'Repeating template':'Current week'}</span></h2><div className="legend"><i className="day"/>Day <i className="evening"/>Evening <i className="night"/>Night Audit</div></div>{base&&<div className="info"><Repeat2/> This base schedule repeats every week. Date-specific time off and sick leave never change this template.</div>}<div className="week">{days.map((d,di)=><article key={d}><header className={di===0?'selected':''}><span>{d.slice(0,3)}</span><b>{5+di}</b>{di===0&&<small>Today</small>}</header>{schedule[d].map(s=>{const e=person(s.employee);return <div className={`shift-card ${s.type.split(' ')[0].toLowerCase()} ${s.open?'open-shift':''}`} key={s.type}><span>{s.type}</span><small>{s.time.replace(' – ','–')}</small>{e?<Person employee={e}/>:<><strong className="needs"><AlertTriangle/> Needs coverage</strong><button>Find coverage</button></>}</div>})}<button className="addshift"><Plus/> Add shift</button></article>)}</div><div className="mobile-hint">Swipe sideways to see all seven days →</div></>}
function Employees(){return <div className="panel employee-panel"><div className="table-tools"><input placeholder="Search employees…"/><select><option>All roles</option></select><button className="primary"><Plus/> Add employee</button></div><div className="employee-table"><div className="tr th"><span>Employee</span><span>Normal shift</span><span>Scheduled</span><span>Target</span><span>Status</span></div>{employees.map(e=><div className="tr" key={e.id}><Person employee={e}/><span>{e.shift}</span><span><b>{e.hours} hrs</b></span><span>{e.target} hrs</span><span><i className="status-dot"/> Active</span></div>)}</div></div>}
function Requests(){return <div className="requests"><div className="tabs"><button className="active">Pending <b>3</b></button><button>Approved</button><button>Denied</button></div>{[{e:employees[1],dates:'Oct 15 – Oct 16',reason:'Family appointment'},{e:employees[4],dates:'Oct 20',reason:'Personal day'},{e:employees[3],dates:'Nov 2 – Nov 4',reason:'Vacation'}].map(x=><div className="panel request" key={x.dates}><Person employee={x.e}/><div><small>DATES REQUESTED</small><strong>{x.dates}</strong></div><div><small>REASON</small><strong>{x.reason}</strong></div><span className="pending">Pending</span><button className="deny">Deny</button><button className="approve">Approve</button></div>)}</div>}
function OpenShifts(){return <div className="open-layout"><div className="panel open-detail"><span className="eyebrow">NEEDS COVERAGE</span><h2>Friday · Day Shift</h2><p><Clock3/> October 9 · 7:00 AM – 3:00 PM</p><div className="callout"><AlertTriangle/><div><b>Sarah Mitchell is away</b><span>Approved time off applies to this date only. Her base schedule is unchanged.</span></div></div><h3>Eligible employees</h3>{[employees[1],employees[3]].map((e,i)=><div className="candidate" key={e.id}><Person employee={e}/><span><b>{e.hours + 8} hrs</b><small>if assigned</small></span>{i===1&&<em>Over target</em>}<button>Assign</button></div>)}</div><div className="panel volunteer"><h3>Coverage requests</h3><div className="empty-icon"><Users/></div><b>No volunteers yet</b><p>Eligible employees can request this shift from their dashboard.</p></div></div>}
function EmployeeView({onLogout}:{onLogout:()=>void}){return <div className="employee-view"><header><div className="brand"><span className="brandmark">M</span><div>Motel Schedule<small>Maker</small></div></div><button className="iconbtn"><Bell/></button><button className="logout-text" onClick={onLogout}>Log out</button></header><main><p className="hello">Good morning, Marcus</p><h1>Here’s your schedule.</h1><div className="next-shift"><span>NEXT SHIFT</span><div className="big-date"><b>6</b><small>OCT<br/>TUE</small></div><div><h2>Evening Shift</h2><p>3:00 PM – 11:00 PM</p></div><em>Tomorrow</em></div><div className="employee-actions"><button><Umbrella/><span><b>Request time off</b><small>Plan ahead</small></span><ArrowRight/></button><button><AlertTriangle/><span><b>Report sick</b><small>For a scheduled shift</small></span><ArrowRight/></button></div><div className="employee-section"><PanelHead title="This week"/><div className="my-week">{days.map((d,i)=><div className={i===0?'past':i===1?'current':''} key={d}><span><b>{d.slice(0,3)}</b><small>{5+i}</small></span>{[1,2,3,4].includes(i)?<><strong>Evening Shift</strong><small>3:00 PM – 11:00 PM</small></>:<em>Off</em>}</div>)}</div></div><div className="employee-section"><PanelHead title="Open shifts"/><div className="available"><div><span>FRI<b>9</b></span><div><strong>Day Shift</strong><small>7:00 AM – 3:00 PM · 8 hours</small></div></div><button>Request to cover</button></div></div></main><nav><button className="active"><CalendarDays/>Schedule</button><button><Clock3/>Open shifts</button><button><Umbrella/>Time off</button><button><UserRound/>Profile</button></nav></div>}
export default App
